server:
    port: 6081
spring:
  application:
    name: patients-service
  cloud:
      config:
        enabled: false
        uri: http://localhost:9296
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka